config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]

  root to: "home#show"
  get 'about', to: 'home#about'

  get 'generator', to: 'generator#index'
  get 'generator/results', to: 'generator#show'

  resources :users
  resources :users do
    get 'user_visits_download', to: 'users#user_visits_download'
  end

  resources :parks, only: [:show, :index]
  resources :vacations

  resources :vacations do
    resources :visits, except: [:show, :index]
  end

  resources :saved_trips

  namespace :api do
    namespace :v1 do
      resources :vacations, only: [:index, :show]
      resources :user_visits, only: [:show]
      resources :parks, only: [:index]
    end
  end

end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :user

  has_many :visits, dependent: :destroy
  has_many :parks, through: :visits

  validates :name, :location, :start_date, :end_date, presence: true
  validates :name, length: { minimum: 5 }
  validates :display_public, inclusion: { in: [true, false], message: "- please select if this vacation should be publicly viewable" }
  validates :description, length: { minimum: 20 }, allow_blank: true
  validate :vacation_has_happened
  validate :dates_acceptable

  def vacation_has_happened
    if (self.start_date) > Date.today
      errors.add("Start date", "cannot be in the future.")
    end
    if (self.end_date) > Date.today
      errors.add("End date", "cannot be in the future.")
    end
  end

  def dates_acceptable
    if (self.start_date > self.end_date)
      errors.add("End date", "must be after the start date.")
    end
  end

  def text_dates
    return "#{self.start_date.strftime "%B %e, %Y"} - #{self.end_date.strftime "%B %e, %Y"}"
  end

  def find_center
    lat_average = (self.visits.map{ |visit| visit.park.latitude }.inject(:+))  / self.visits.count
    lng_average = (self.visits.map{ |visit| visit.park.longitude }.inject(:+)) / self.visits.count
    return [lat_average.round(3), lng_average.round(3)]
  end

  def find_zoom

  end

end

app/controllers/api/v1/vacations_controller.rb
class Api::V1::VacationsController < ApplicationController

  # can be revised to supply a map of all parks and basic stats
  def index
    # list = Visit.all.map { |visit|
    #   {
    #     id: visit.id,
    #     user_id: visit.user_id,
    #     vacation_id: visit.vacation_id,
    #     name: visit.park.name,
    #     full_name: visit.park.full_name,
    #     visit_date: visit.text_dates,
    #     lat: visit.park.latitude,
    #     lng: visit.park.longitude
    #     }
    #   }
    #
    # render json: list
  end

  def show
    @vacation = Vacation.find(params[:id])

    list = @vacation.visits.map { |visit|
      {
        id: visit.id,
        user_id: visit.user_id,
        vacation_id: visit.vacation_id,
        name: visit.park.name,
        full_name: visit.park.full_name,
        visit_date: visit.text_dates,
        lat: visit.park.latitude,
        lng: visit.park.longitude
        }
      }

    render json: list
  end

end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :authorize_sign_in, except: [:show, :index]
  before_action :authorize_view_permission, only: [:show]
  before_action :authorize_management, only: [:edit, :update, :destroy]

  def index
    @vacations = Vacation.where(display_public: true)
  end

  def show
    @vacation = Vacation.where(id: params[:id]).first
    @visits = @vacation.visits
    if !@visits.empty?
      @map_center = @vacation.find_center
    end
    if current_user == @vacation.user
      @private_table = true
    end
  end

  def new
    @vacation = Vacation.new
    @public_choice = [true, false]
  end

  def create
    @vacation = Vacation.new(vacation_params)
    @vacation.user_id = current_user.id

    if @vacation.save
      flash[:notice] = "Vacation created!"
      redirect_to vacation_path(@vacation)
    else
      flash[:alert] = "Vacation not created"
      render :new
    end
  end

  def edit
    @vacation = Vacation.where(id: params[:id]).first
    @public_choice = [true, false]
  end

  def update
    @vacation = Vacation.find(params[:id])
    @vacation.update(vacation_params)
    @vacation.user_id = current_user.id

    if @vacation.save
      flash[:notice] = "Vacation has been updated."
      redirect_to vacation_path(@vacation)
    else
      flash[:alert] = "Update failed."
      render :edit
    end
  end

  def destroy
    @vacation = Vacation.find(params[:id])
    @vacation.destroy
    redirect_to vacations_path
  end


  private

  def vacation_params
    params.require(:vacation).permit(
      :name, :location, :description, :start_date, :end_date, :display_public
    )
  end

  def authorize_sign_in
    if current_user.nil?
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def authorize_view_permission
    if !(current_user == Vacation.find(params[:id]).user) && (Vacation.find(params[:id]).display_public == false)
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def authorize_management
    if !(current_user && current_user.vacations.include?(Vacation.find(params[:id])))
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

end

app/views/vacations/_form.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_PLACES_KEY'] %>&libraries=places&callback=initAutocomplete" async defer></script>

<%= form_for(@vacation) do |f| %>
  <% if @vacation.errors.any? %>
    <div id="new-vacation-error">
      <h2><%= pluralize(@vacation.errors.count, "error") %> in Vacation creation:</h2>
      <ul>
        <% @vacation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

    </div>
  <% end %>

  <%= f.label :name, "Vacation Name" %>
  <%= f.text_field :name %>
  <%= f.label :location, "Location" %>
  <%= f.text_field :location, id: "autocomplete" %>

  <%= f.label :description, "Description (optional)" %>
  <%= f.text_area :description %><br>

  <%= f.label :start_date, "Start Date" %>
  <%= f.date_select :start_date, start_year: 1900, end_year: Time.now.year %><br>

  <%= f.label :end_date, "End Date" %>
  <%= f.date_select :end_date, start_year: 1900, end_year: Time.now.year %><br>


  <p>Do you want this vacation to be public?</p>
  <%= f.radio_button :display_public, true %>
  <%= f.label :display_public, "Yes", value: true %>
  <%= f.radio_button :display_public, false %>
  <%= f.label :display_public, "No", value: false %>

  <br><br>

  <%= f.submit "Create Vacation", class: "button" %>

  <br><br>

<% end %>

app/views/vacations/_table_private.html.erb
<div class="user-vacations-table">
  <table>
    <thead>
      <tr>
        <th width="300">Location</th>
        <th width="140">Arrived</th>
        <th width="140">Departed</th>
        <th width="50">Management</th>
      </tr>
    </thead>
    <tbody>
      <% @visits.each do |visit| %>
      <tr>
        <td><%= link_to "#{visit.park.full_name}", park_path(visit.park) %></td>
        <td><%= visit.start_date_display %></td>
        <td><%= visit.end_date_display %></td>
        <td>
          <%= link_to "Edit", edit_vacation_visit_path(@vacation, visit) %>
          - <%= link_to "Delete", [@vacation, visit], data: { confirm: "Are you sure you want to delete this visit to #{visit.park.full_name}?" }, method: :delete %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/vacations/_table_public.html.erb
<div class="user-vacations-table">
  <table>
    <thead>
      <tr>
        <th width="300">Location</th>
        <th width="140">Arrived</th>
        <th width="140">Departed</th>
      </tr>
    </thead>
    <tbody>
      <% @visits.each do |visit| %>
      <tr>
        <td><%= link_to "#{visit.park.full_name}", park_path(visit.park) %></td>
        <td><%= visit.start_date_display %></td>
        <td><%= visit.end_date_display %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/vacations/edit.html.erb
<div class="row">
  <h1>Edit details for: <%= @vacation.name %></h1>

  <div class="row">
    <div class="large-6 columns">
      <%= render 'form' %>
    </div>
  </div>

  <%= button_to "Delete this Vacation", vacation_path(@vacation), data: { confirm: "Are you sure you want to delete:\n #{@vacation.name}?" }, method: :delete %>
  <br><br>
</div>

app/views/vacations/index.html.erb
<div class="row">
  <h1>All Logged Vacations</h1>

  <% if current_user %>
    <%= link_to "Create a new vacation", new_vacation_path %>
  <% end %>


  <table id="vacationsTable" class="tablesorter">
    <thead>
      <tr>
        <th width="500">Vacation Name</th>
        <th width="250">Location</th>
        <th width="250">Dates</th>
        <% if current_user %>
          <th width="250">Submitted by</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @vacations.each do |vacation| %>
      <tr>
        <td><%= link_to "#{vacation.name}", vacation_path(vacation) %></td>
        <td><%= vacation.location %></td>
        <td><%= vacation.text_dates %></td>
        <% if current_user %>
          <td><%= link_to "#{vacation.user.name}", user_path(vacation.user) %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/vacations/new.html.erb
<div class="row">
  <h1>Create a new Vacation</h1>
  <div class="row">
    <div class="large-6 columns">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/vacations/show.html.erb
<div class="row">
  <div class="columns medium-12">

    <%= link_to "Back to all vacations", vacations_path %>

    <h2>Vacation: <%= @vacation.name %></h2>
    <h4>By:
      <% if current_user %>
        <%= link_to "#{@vacation.user.name}", user_path(@vacation.user) %>
      <% else %>
        <%= @vacation.user.name %>
      <% end %>
    </h4>
    <% if current_user == @vacation.user %>
      <%= link_to "Edit this Vacation", edit_vacation_path(@vacation), class:"" %> -
      <%= link_to "Add a Visit", new_vacation_visit_path(@vacation)  , class:"" %>
    <% end %>

  </div>
</div>

<div class="row">
  <div class="columns small-12">
    <strong>Location:</strong> <%= @vacation.location %><br>
    <strong>Vacation Dates:</strong> <%= @vacation.text_dates %><br>
    <% if !@vacation.description.empty? %>
      <strong>Description:</strong> <%= @vacation.description %>
    <% end %>
  </div>
</div>

<br>

<div class="row">
  <div class="columns small-12">
    <% if @private_table %>
      <%= render 'table_private' %>
    <% else %>
      <%= render 'table_public' %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="columns medium-12">

    <% if @map_center %>
      <h3>Map of Vacation</h3>
      <div id="map">
        <%= javascript_tag do %>
          window.vacation_location = '<%= @vacation.location %>';
          window.vacation_id = <%= @vacation.id %>;
          window.map_center = <%= @map_center %>;
        <% end %>
        <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_JAVASCRIPT_KEY']}&callback=initVacationMap" %>
      </div>
    <% end %>

  </div>
</div>