config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]

  root to: "home#show"
  get 'about', to: 'home#about'

  get 'generator', to: 'generator#index'
  get 'generator/results', to: 'generator#show'

  resources :users
  resources :users do
    get 'user_visits_download', to: 'users#user_visits_download'
  end

  resources :parks, only: [:show, :index]
  resources :vacations

  resources :vacations do
    resources :visits, except: [:show, :index]
  end

  resources :saved_trips

  namespace :api do
    namespace :v1 do
      resources :vacations, only: [:index, :show]
      resources :user_visits, only: [:show]
      resources :parks, only: [:index]
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  require 'csv'

  has_many :visits
  has_many :vacations

  has_many :parks, through: :visits

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_sign_in
  before_action :authorize_edit, only: [:edit, :update, :destroy]
  before_action :authorize_map_download, only: [:user_visits_download]

  CURRENT_DATE = Time.now.strftime("%d%m%Y")

  def omniauth_failure
    flash[:alert] = "There an error signing in with Google. Please try again."
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])

    if current_user == @user
      @vacations = @user.vacations
      @private_table = true
    else
      @vacations = @user.vacations.where(display_public: true)
    end

    if !@user.vacations.empty?
      @download_path = "https://s3.amazonaws.com/vacation-tracker/Visited_Parks_#{CURRENT_DATE}_#{@user.uid}.kml"
    else
      @download_path = "https://s3.amazonaws.com/vacation-tracker/blank_map_all_visits.kml"
    end
    
    # @saved_trips = User.saved_trips
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    session[:user_id] = nil
    @user.destroy
    redirect_to root_path
  end

  def user_visits_download
    if params[:user_id].nil?
      redirect_to root_path
    else
      @user = User.find(params[:user_id])
      if @user.parks.empty?
        @download_path = "https://s3.amazonaws.com/vacation-tracker/blank_map_all_visits.kml"
      else
        map_data = UserVisitsSerializer.perform(@user)
        print_data = KmlWriter.write_kml(map_data, @user.uid)
        MapUploader.perform(print_data)
        @download_path = "https://s3.amazonaws.com/vacation-tracker/Visited_Parks_#{CURRENT_DATE}_#{@user.uid}.kml"
      end
    end
    render "map_download"
  end

  private

  def authorize_sign_in
    if current_user.nil?
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def authorize_edit
    if current_user.id != params[:id].to_i
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def authorize_map_download
    if current_user.id != params[:user_id].to_i
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

end

app/views/users/_vacations_table_private.html.erb
<h4>Vacations</h4>
<div class="user-vacations-table">
  <table>
    <thead>
      <tr>
        <th width="450">Vacation Name</th>
        <th width="250">Location</th>
        <th width="300">Dates</th>
        <th width="100">Public?</th>
        <th width="100"></th>
      </tr>
    </thead>
    <tbody>
      <% @vacations.each do |vacation| %>
      <tr>
        <td><%= link_to "#{vacation.name}", vacation_path(vacation) %></td>
        <td><%= vacation.location %></td>
        <td><%= vacation.text_dates %></td>
        <td>
          <% if vacation.display_public == true %>
            Yes
          <% else %>
            No
          <% end %>
        </td>
        <td><%= link_to "Edit", edit_vacation_path(vacation) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_vacations_table_public.html.erb
<h4>Vacations</h4>
<div class="user-vacations-table">
  <table>
    <thead>
      <tr>
        <th width="450">Vacation Name</th>
        <th width="250">Location</th>
        <th width="300">Dates</th>
      </tr>
    </thead>
    <tbody>
      <% @vacations.each do |vacation| %>
      <tr>
        <td><%= link_to "#{vacation.name}", vacation_path(vacation) %></td>
        <td><%= vacation.location %></td>
        <td><%= vacation.text_dates %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<div class="row">
  <h1>Account Management</h1>

  <p>
    Unhappy? <%= button_to "Delete Account", user_path(@user), data: { confirm: "Are you sure?" }, method: :delete %>
  </p>
</div>

app/views/users/map_download.html.erb
<div class="row">
  <%= javascript_tag do %>
    window.download_path = '<%= @download_path %>';
  <% end %>

  <div id="download-instructions" class="column large-8">
    <a href="<%= @download_path %>" download>Download your .KML to use with Google</a>
    <h5>How to use this map in Google My Maps</h5>
    <ol>
      <li>Download the .kml file (click to download or right-click and save).</li>
      <li>Head to the Google <a href="https://www.google.com/maps/d/u/0/" target="_blank">My Maps</a> page.</li>
      <li>Click the "+Create A New Map" button.</li>
      <li>Click the blue Import button within the layer to upload the map data.</li>
    </ol>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <h2>Profile for <%= @user.name %></h2>

  <% if current_user.id == @user.id %>
    <%= link_to "Account Management", edit_user_path(@user) %>
  <% end %>

  <% if @vacations %>
    <% if @private_table %>
      <%= render "vacations_table_private" %>
    <% else %>
      <%= render "vacations_table_public" %>
    <% end %>
  <% else %>
    <h5>This user has not logged any vacations yet.</h5>
  <% end %>

  <br>

  <h3>Map of Visited Parks</h3>
  <div id="map">
    <%= javascript_tag do %>
      window.user_id = <%= @user.id %>;
    <% end %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_JAVASCRIPT_KEY']}&callback=initUserMap" %>
  </div>
  <br>

  <% if (current_user == @user) %>
    <%= javascript_tag do %>
      window.download_path = '<%=@download_path%>';
    <% end %>

    <div id="download-area" class="row">
      <div id="download-link-area" class="column large-4 text-center">
        <%= link_to "Export this map to Google My Maps", user_user_visits_download_path(@user), class: "button", id: "map-download-button" %>
      </div>

      <div id="download-instructions" class="column large-8">
        <h5>How to edit this map in Google My Maps</h5>
        <ol>
          <li>Click the button above to generate the download link.</li>
          <li>Download the .kml file (click to download or right-click and save).</li>
          <li>Head to the Google <a href="https://www.google.com/maps/d/u/0/" target="_blank">My Maps</a> page.</li>
          <li>Click the "+Create A New Map" button.</li>
          <li>Click the blue Import button within the layer to upload the map data.</li>
        </ol>
      </div>
    </div>

    <br>
  <% end %>
</div>