config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]

  root to: "home#show"
  get 'about', to: 'home#about'

  get 'generator', to: 'generator#index'
  get 'generator/results', to: 'generator#show'

  resources :users
  resources :users do
    get 'user_visits_download', to: 'users#user_visits_download'
  end

  resources :parks, only: [:show, :index]
  resources :vacations

  resources :vacations do
    resources :visits, except: [:show, :index]
  end

  resources :saved_trips

  namespace :api do
    namespace :v1 do
      resources :vacations, only: [:index, :show]
      resources :user_visits, only: [:show]
      resources :parks, only: [:index]
    end
  end

end

app/views/layouts/_footer.html.erb
<!-- Start footer -->
<footer class="footer">
  <ul class="menu">
    <li><%= link_to "Parks", parks_path %></li>
    <li><%= link_to "Vacations", vacations_path %></li>
    <li><%= link_to "Generator", generator_path %></li>
    <li><%= link_to "About", about_path %></li>
  </ul>
</div>
<!-- End footer -->

app/views/layouts/_nav_bar.html.erb
<!-- Start Top Bar -->
<div class="top-bar">

  <div class="top-bar-left">
    <ul class="menu">
      <li>
        <div id="home-button-container">
          <a id="home-button-link" href="/"> <img id="home-button-image" src="https://s3.amazonaws.com/vacation-tracker/support/home_button_rectangle-transparent.png"> </a>
        </div>
      </li>
      <li><%= link_to "Parks", parks_path %></li>
      <li><%= link_to "Vacations", vacations_path %></li>
      <li><%= link_to "Trip Generator", generator_path %></li>
    </ul>
  </div>

  <div class="top-bar-right">
    <ul class="menu">
      <% if current_user %>
        <li class="sign-in-status">Signed in as <strong><%= current_user.name %>!</strong><li>
        <li><%= link_to "My Account", user_path(current_user) %></li>
        <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
      <% else %>
        <li><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
      <% end %>
    </ul>
  </div>

</div>
<!-- End Top Bar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="https://s3.amazonaws.com/vacation-tracker/support/VacationTracker_Logo-01.png">
    <title><%= content_for?(:title) ? yield(:title) : "Vacation Tracker" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
    <%= csrf_meta_tags %>

    <meta name="theme-color" content="#178d4f">
    <meta name="description" content="Tool for tracking vacations, mapping trips, and generating possible adventures through the US National Parks." />
    <link rel="icon" sizes="192x192" href="https://s3.amazonaws.com/vacation-tracker/support/VacationTracker_Logo-01.png">

  </head>

  <%= render "layouts/nav_bar" %>

  <body>
    <% if flash[:notice] || flash[:alert] %>
      <div class="callout align-center">
        <p class="notice row"><%= notice %></p>
        <p class="alert row"><%= alert %></p>
      </div>
    <% end %>

    <%# NOTE: each .erb requires the contents be wrapped in a <div class="row"></div> %>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
    <script>
      $(document).foundation();
    </script>

  </body>
  <%= render "layouts/footer" %>

</html>